language: rust
rust:
- nightly
- beta
- stable
addons:
  apt:
    packages:
    - libgtk-3-dev
    - libsoup2.4-dev
    - webkit2gtk-4.0 
env:
  - GTK=3.4
  - GTK=3.18
  - GTK=3.22.30
script:
  - cargo build ---features gtk_3_18