language: rust
rust:
- stable
addons:
  apt:
    packages:
    - libgtk-3-dev
    - libsoup2.4-dev
    - webkit2gtk-4.0

env:
  - GTK=3.18

before_script:
  - rustup component add rustfmt

script:
  - cargo fmt --all
  - cargo build ---features gtk_3_18 --release

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "target/release/illumination"
  skip_cleanup: true
  on:
    tags: true
