dist: xenial
language: rust
matrix:
  include:
    - os: linux
      rust: nightly
      env: GTK=3.14 FEATURES=futures
    - os: linux
      rust: nightly
      env: GTK=3.24 FEATURES=v3_16,futures
    - os: linux
      rust: beta
      env: GTK=3.14 FEATURES=
    - os: linux
      rust: beta
      env: GTK=3.24 FEATURES=v3_16
    - os: linux
      rust: stable
      env: GTK=3.14 FEATURES=
    - os: linux
      rust: stable
      env: GTK=3.24 FEATURES=v3_16
    - os: linux
      rust: 1.36.0
      env: GTK=3.14 FEATURES=
    - os: linux
      rust: 1.36.0
      env: GTK=3.24 FEATURES=v3_16
    - os: osx
      rust: nightly
      env: GTK=3.14 FEATURES=futures
    # - os: osx
    #   rust: nightly
    #   env: GTK=3.24 FEATURES=v3_16
    - os: osx
      rust: beta
      env: GTK=3.14 FEATURES=
    # - os: osx
    #   rust: beta
    #   env: GTK=3.24 FEATURES=v3_16
    - os: osx
      rust: stable
      env: GTK=3.14 FEATURES=
    # - os: osx
    #   rust: stable
    #   env: GTK=3.24 FEATURES=v3_16
addons:
  apt:
    packages:
    - libgtk-3-dev
    - libmount-dev
    - libsoup2.4-1
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libffi gtk+3 cairo atk libsoup; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig;
    fi
script:
  - rustc --version
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ] && [ "$GTK" == "3.14" ]; then
    cargo install rustfmt;
    make regen_check;
    fi
  - cargo build
  - cargo fmt --all
  - rustc --version
  - mkdir .cargo
  - echo 'paths = ["."]' > .cargo/config
  - git clone https://github.com/oknozor/illumination.git _illumination
  - cd _illumination